{
 "title": "OPS Dashboard Per Site - support",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site_name",
    "label": "Choose Site Name",
    "query": {
     "query": "label_values(swimmer_count,site_name)"
    }
   },
   {
    "name": "server",
    "label": "Choose the servers",
    "query": {
     "query": "label_values(swimmer_count{site_name=~\"$site_name\"},environment)"
    }
   },
   {
    "name": "pool_name",
    "label": "Choose Pool Name",
    "query": {
     "query": "label_values(swimmer_count{site_name=~\"$site_name\"},pool_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(cpu) (node_cpu_seconds_total{instance=\"$server\", job=\"nodeexporter\"}))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$server\", job=\"nodeexporter\"} - node_boot_time_seconds{instance=\"$server\", job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$server\",job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "GPU Card",
   "type": "stat",
   "description": "The official product name of the GPU. This is an alphanumeric string. For all products.",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_gpu_info{instance=\"$server\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Driver Version",
   "type": "stat",
   "description": "The version of the installed NVIDIA display driver. This is an alphanumeric string.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_gpu_info{instance=\"$server\"}",
     "legendFormat": "{{driver_version}}"
    }
   ]
  },
  { "title": "System status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Docker Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "avg by (environment, name) (increase(container_start_time_seconds{environment=~\"$server\", name!=\"\"}[$__rate_interval])) < bool 1",
     "legendFormat": "{{environment}} - {{name}}"
    }
   ]
  },
  {
   "title": "CVS Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "cvs_general_status_v2{environment=~\"$server\", site_name=~\"$site_name\", pool_name=~\"$pool_name\"}",
     "legendFormat": "{{site_name}} {{pool_name}}"
    }
   ]
  },
  {
   "title": "Publish Message To Cloud",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "increase(iot_mqtt{environment=\"$server\", site_name=\"$site_name\", pool_name=\"$pool_name\", error=\"false\"}[10m]) > bool 0",
     "legendFormat": "{{site_name}} {{pool_name}}"
    }
   ]
  },
  {
   "title": "Exceptions per service",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service, exception_name) (\n  increase(cvs_exc_per_service{environment=\"$server\", exception_name!~\"SystemExit|KeyboardInterrupt\"}[$__range])\n)",
     "legendFormat": "{{service}} - {{exception_name}}"
    }
   ]
  },
  {
   "title": "Exceptions per service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by(service) (cvs_exc_per_service{environment=\"$server\", exception_name!~\"SystemExit|KeyboardInterrupt\"})",
     "legendFormat": "{{service}} - {{exception_name}}"
    }
   ]
  },
  {
   "title": "Pool Offline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "increase(pool_offline{site_name=~\"$site_name\", pool_name=~\"$pool_name\"}[10m]) > bool 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Closed Ports",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "increase(cvs_test_connection_failed{environment=\"$server\"}[1h])",
     "legendFormat": "{{address_name}} {{port}}"
    }
   ]
  },
  {
   "title": "SpeedTest",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "download_speed_bps{instance=\"$server\"}",
     "legendFormat": "Download"
    },
    {
     "expr": "upload_speed_bps{instance=\"$server\"}",
     "legendFormat": "Upload"
    }
   ]
  },
  { "title": "Camera metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "OCR vs SystemTime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "ocr_failure{site_name=\"$site_name\", pool_name=\"$pool_name\"} > bool 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Video Stream Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "increase(video_stream_error_v2{environment=~\"$server\", site_name=~\"$site_name\", pool_name=~\"$pool_name\"}[$__rate_interval]) > bool 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Camera configurator",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "camera_configurator{environment=\"$server\", pool_name=\"$pool_name\", error=\"true\"}",
     "legendFormat": "Camera - {{camera}}"
    },
    {
     "expr": "camera_configurator{environment=\"$server\", pool_name=\"$pool_name\", error=\"false\"}",
     "legendFormat": "Camera - {{camera}}"
    }
   ]
  },
  {
   "title": "No Ping to Camera",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "camera_ping{site_name=\"$site_name\", pool_name=\"$pool_name\", ping=\"False\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max seconds between frames",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_time_between_frames{site_name=\"$site_name\", pool_name=\"$pool_name\"}",
     "legendFormat": "{{site_name}}_{{pool_name}}_{{camera_id}}"
    }
   ]
  },
  { "title": "Masking Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Static Masking",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "static_mask{environment=~'$server', site_name=~'$site_name', pool_name=~'$pool_name'}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Algo fps - Per Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Max Time Between Frames",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "max_time_between_frames{environment=~\"$server\", site_name=~\"$site_name\", pool_name=~\"$pool_name\"}",
     "legendFormat": "{{site_name}}_{{pool_name}}_{{camera_id}}"
    }
   ]
  },
  {
   "title": "Actual fps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "actual_fps{environment=~\"$server\", site_name=~\"$site_name\", pool_name=~\"$pool_name\"}",
     "legendFormat": "{{site_name}}_{{pool_name}}_{{camera_id}}"
    }
   ]
  },
  {
   "title": "Video Stream fps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "video_stream_fps{environment=~\"$server\", site_name=~\"$site_name\", pool_name=~\"$pool_name\"}",
     "legendFormat": "{{site_name}}_{{pool_name}}"
    }
   ]
  },
  {
   "title": "Detection fps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "detection_fps{environment=~\"$server\", site_name=~\"$site_name\", pool_name=~\"$pool_name\"}",
     "legendFormat": "{{site_name}}_{{pool_name}}"
    }
   ]
  },
  {
   "title": "Ctm fps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "ctm_fps{environment=~\"$server\", site_name=~\"$site_name\", pool_name=~\"$pool_name\"}",
     "legendFormat": "{{site_name}}_{{pool_name}}"
    }
   ]
  },
  {
   "title": "Gtm fps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "tracking_fps{environment=~\"$server\", site_name=~\"$site_name\", pool_name=~\"$pool_name\"}",
     "legendFormat": "{{site_name}}_{{pool_name}}"
    }
   ]
  },
  {
   "title": "Decision Engine fps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "decisions_engine_fps{environment=~\"$server\", site_name=~\"$site_name\", pool_name=~\"$pool_name\"}",
     "legendFormat": "{{site_name}}_{{pool_name}}"
    }
   ]
  },
  { "title": "General System Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$server\",job=\"nodeexporter\", mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$server\",job=\"nodeexporter\"}[$__rate_interval])))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$server\",job=\"nodeexporter\", mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$server\",job=\"nodeexporter\"}[$__rate_interval])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$server\",job=\"nodeexporter\", mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$server\",job=\"nodeexporter\"}[$__rate_interval])))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$server\",job=\"nodeexporter\", mode=~\".*irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$server\",job=\"nodeexporter\"}[$__rate_interval])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$server\",job=\"nodeexporter\", mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$server\",job=\"nodeexporter\"}[$__rate_interval])))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$server\",job=\"nodeexporter\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$server\",job=\"nodeexporter\"}[$__rate_interval])))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$server\",job=\"nodeexporter\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$server\",job=\"nodeexporter\"} - node_memory_MemFree_bytes{instance=\"$server\",job=\"nodeexporter\"} - (node_memory_Cached_bytes{instance=\"$server\",job=\"nodeexporter\"} + node_memory_Buffers_bytes{instance=\"$server\",job=\"nodeexporter\"} + node_memory_SReclaimable_bytes{instance=\"$server\",job=\"nodeexporter\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$server\",job=\"nodeexporter\"} + node_memory_Buffers_bytes{instance=\"$server\",job=\"nodeexporter\"} + node_memory_SReclaimable_bytes{instance=\"$server\",job=\"nodeexporter\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$server\",job=\"nodeexporter\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$server\",job=\"nodeexporter\"} - node_memory_SwapFree_bytes{instance=\"$server\",job=\"nodeexporter\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$server\",job=\"nodeexporter\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"$server\",job=\"nodeexporter\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic(EXT?/XFS)",
   "type": "table-old",
   "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$server',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$server',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$server',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$server',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$server',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$server',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$server',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "mean fuse error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "mean_fuse_error{environment=~\"$server\",site_name=~\"$site_name\", pool_name=~\"$pool_name\"}",
     "legendFormat": "{{site_name}}_{{pool_name}} - camera {{camera_id}}"
    }
   ]
  },
  {
   "title": "Maintenance Mode",
   "type": "timeseries",
   "description": "Maintenance flag is set to true while the server is going through maintenance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "targets": [
    {
     "expr": "cvs_maintenance_mode{environment=~\"$server\", site_name=~\"$site_name\", pool_name=~\"$pool_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tailscale status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "increase(cvs_tailscale_status_v3{environment=\"$server\"}[$__rate_interval]) > bool 0",
     "legendFormat": "{{site_name}} {{pool_name}}"
    }
   ]
  },
  {
   "title": "Swimmer Count",
   "type": "timeseries",
   "description": "Amount of swimmers in the pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "targets": [
    {
     "expr": "swimmer_count{environment=~\"$server\", site_name=~\"$site_name\", pool_name=~\"$pool_name\"}",
     "legendFormat": "{{site_name}}_{{pool_name}}"
    }
   ]
  },
  {
   "title": "Hardware temperature monitor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$server\",job=\"nodeexporter\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{instance=\"$server\",job=\"nodeexporter\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "GPU Fan Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "increase(cvs_gpu_status_v3{environment=\"$server\", site_name=\"$site_name\"}[$__rate_interval]) > bool 0",
     "legendFormat": "{{site_name}} {{pool_name}}"
    }
   ]
  },
  {
   "title": "SM Clock Speed",
   "type": "graph",
   "description": "Current frequency of SM (Streaming Multiprocessor) clock.",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_sm_clock_hz{instance=\"$server\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 139 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=\"$server\", gpu=\"0\"}",
     "legendFormat": "{{instance}} GPU {{gpu}}"
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "TimeLine status",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 148 },
   "targets": [
    {
     "expr": "cvs_general_status_v2{environment=~\"$server\", site_name=~\"$site_name\", pool_name=~\"$pool_name\"} *20\n",
     "legendFormat": "CVS STATUS"
    },
    {
     "expr": "(1 -increase(pool_offline{site_name=~\"$site_name\", pool_name=~\"$pool_name\"}[10m]) > bool 0) *20",
     "legendFormat": "POOL Connectivity"
    },
    {
     "expr": "(increase(iot_mqtt{environment=\"$server\", site_name=\"$site_name\", pool_name=\"$pool_name\", error=\"false\"}[10m]) > bool 0)*20",
     "legendFormat": "Publish message to cloud"
    },
    {
     "expr": "(detection_fps{environment=\"$server\", site_name=\"$site_name\", pool_name=\"$pool_name\"} > bool 0.6) * 20",
     "legendFormat": "Detection FPS"
    },
    {
     "expr": "(sum by(environment) (DCGM_FI_DEV_GPU_TEMP{instance=\"$server\", gpu=\"0\"}) < bool 95)*20",
     "legendFormat": "GPU TEMP"
    },
    {
     "expr": "(2-((increase(cvs_tailscale_status_v3{environment=\"$server\"}[$__rate_interval]) > bool 0)*2))*10",
     "legendFormat": "Tailscale"
    },
    {
     "expr": "(2-((increase(cvs_gpu_status_v3{environment=\"$server\", site_name=\"$site_name\"}[$__rate_interval]) > bool 0)*2))*10",
     "legendFormat": "GPU Fan Error"
    },
    {
     "expr": "(nvidia_smi_clocks_current_sm_clock_hz{instance=\"$server\"} > bool 1000000000)*20",
     "legendFormat": "GPU clock Speed"
    },
    {
     "expr": "(2-((sum by(pool_name) (increase(video_stream_error_v2{environment=\"$server\", site_name=\"$site_name\", pool_name=\"$pool_name\"}[$__rate_interval])) > bool 0)*2))*10",
     "legendFormat": "Video Stream Error"
    }
   ]
  }
 ]
}